### ISSUE TITLE
Be nice to clearly state that you need to be using CMake

### ISSUE THREAD

**Issue by toby-allsopp** [tomtom-international/cpp-dependencies#13]
The README didn't make it clear to me that it needs CMakeLists.txt to do anything useful. I managed to get it building on WIndows but our code uses MSVC projects so all I got was:

```
1 components with 0 public dependencies, 0 private dependencies
Detected 0 nodes in cycles
```

**Comment by dascandy** [comment]
It needs to have some way to recognize componentization (because otherwise it'll just see one component, as you noticed), and right now it uses cmakefiles to find the component locations (but no more than that).

You can work around it by tagging every folder with an empty CMakeLists.txt file, no content is necessary for this purpose. 

Based on a Reddit comment I'm adding a flag to make it infer components from the directory structure.

**Comment by toby-allsopp** [comment]
Ah, I didn't realise they could be empty!

Quick conversion script: `find Source/ -name '*.vcxproj' | while read p; do touch $(dirname $p)/CMakeLists.txt; done` gets it doing something.

Thanks.

**Comment by dascandy** [comment]
I've since tested the inferring of components and it seems to have the problems I was expecting - it recognizes the "src" and "include" folders as separate components, which breaks the dependency analysis (as all src folders depend on include folders, and all private dependencies are completely hidden). I'll leave it in as it does make it possible to analyze your code if you have merged components, but it has its flaws.

Will close this issue when that hits the main codeline.

**Comment by toby-allsopp** [comment]
I found that creating empty `CMakeLists.txt` files allows it to pick up my components but not any dependencies. I guess it needs to know include paths and stuff.

**Comment by dascandy** [comment]
If you are checking this on Windows (which given the vcxproj's I assume you are) that has a known problem of not finding the includes (issue #4) as it assumes Unix separators in the paths. I've fixed that since on my personal fork (dascandy/cpp-dependencies) and I'll merge that in soon enough, but after showing it stable. That branch is red on travis and appveyor, but only because they test more than this one does and the new things are broken wrt CI. Can you see if that branch works for you too? I've tested it here and it works well enough on my test project.

**Comment by dascandy** [comment]
Windows support updated; "--infer" added for it to guess your components without a resemblance of CMake.

**Comment by toby-allsopp** [comment]
Thanks!

`--infer` didn't work for my source layout but with empty CMakeLists it actually detects some dependencies now!
