### ISSUE TITLE
Support Mac OS X

### ISSUE THREAD

**Issue by mbitsnbites** [tomtom-international/cpp-dependencies#27]
In Input.cpp, the Linux function memrchr() is used. This is a non-standard function, and should be east to replace by something more portable.

**Comment by maikelvdh** [comment]
Alternatively you can just use the HAS_MEMRCHR option when configuring with CMake (by using -DHAS_MEMRCHR=OFF parameter) then you have a working cpp-dependencies on OSX already.

**Comment by dascandy** [comment]
It is an optimization that only helps if you have a fast memrchr. It allows the parser to stop reading when there will be no more includes following, making it skip 90%+ of most source code files. And if your memrchr is SSE optimized that'll skip 16 bytes per few cycles.

But of course, if you have no optimized memrchr it'll be per-character and that won't speed it up much.

I'll cross-integrate the CL that makes the cmakefile have decent defaults per platform instead of a universal one, because on OSX the flag should be off by default.

**Comment by dascandy** [comment]
Integrated fix for cmakelists to have sensible per-platform defaults.
